"use client";

import { CheckCircle2, LoaderCircle, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { type FormEvent, useState } from "react";

import { adminRequest } from "./admin-api";

export function InvitationAcceptClient({ token, invitation }: { token: string; invitation: { email: string; displayName: string; expiresAt: string } }) {
  const [displayName, setDisplayName] = useState(invitation.displayName); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [accepted, setAccepted] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (password !== confirm) { setError("Passwords do not match."); return; } setPending(true); setError(null); try { await adminRequest(`/api/invitations/${token}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ displayName, password }) }); setAccepted(true); } catch (value) { setError(value instanceof Error ? value.message : "The invitation could not be accepted."); } finally { setPending(false); } }
  return <main className="invitation-page"><Link className="wordmark" href="/">Askme <span aria-hidden="true">问候</span></Link><section className="invitation-card">{accepted ? <div className="admin-empty large"><CheckCircle2 size={42} /><h1>Admin account created</h1><p>{invitation.email} can now sign in with the new password.</p><Link className="primary-button" href="/login">Go to sign in</Link></div> : <><span className="invitation-icon"><ShieldCheck size={28} /></span><p className="page-kicker">One-time Admin invitation</p><h1>Join Askme administration</h1><p>Invitation for <strong>{invitation.email}</strong>. It expires {new Date(invitation.expiresAt).toLocaleString("en-US", { timeZone: "UTC" })}.</p>{error ? <div className="inline-feedback error" role="alert">{error}</div> : null}<form onSubmit={submit}><label>Display name<input required minLength={1} maxLength={120} value={displayName} onChange={(event) => setDisplayName(event.target.value)} /></label><label>Password<input type="password" required minLength={12} maxLength={200} value={password} onChange={(event) => setPassword(event.target.value)} /></label><label>Confirm password<input type="password" required minLength={12} maxLength={200} value={confirm} onChange={(event) => setConfirm(event.target.value)} /></label><button className="primary-button" disabled={pending || password.length < 12 || password !== confirm}>{pending ? <LoaderCircle className="spin" size={16} /> : <ShieldCheck size={16} />}{pending ? "Creating account…" : "Accept Invitation"}</button></form></>}</section></main>;
}
