"use client";

import { Bot, MessageSquareText, Quote, ShieldAlert, TrendingUp, UsersRound } from "lucide-react";
import { useState } from "react";

import { adminRequest } from "./admin-api";
import { AdminTrendChart, type AdminTrendPoint, type TrendKey, trendLabels } from "./trend-chart";

type Report = { range: "7d" | "30d" | "90d"; totals: { totalCandidates: number; publishedAgents: number; activeInterviews: number; citationUsage: number; flaggedContent: number }; trend: AdminTrendPoint[]; hasData: boolean; distributions: { aiOutcomes: Array<{ outcome: string; count: number }>; candidateStatus: Array<{ status: string; count: number }>; publicationStatus: Array<{ status: string; count: number }>; reviewStatus: Array<{ status: string; count: number }> } };

const metricDefinitions = [
  { key: "totalCandidates", label: "Candidates", icon: UsersRound }, { key: "publishedAgents", label: "Published Agents", icon: Bot },
  { key: "activeInterviews", label: "Active Interviews", icon: MessageSquareText }, { key: "citationUsage", label: "Citations", icon: Quote }, { key: "flaggedContent", label: "Open Reviews", icon: ShieldAlert },
] as const;

export function ReportsClient({ initialReport }: { initialReport: Report }) {
  const [report, setReport] = useState(initialReport); const [series, setSeries] = useState<TrendKey>("candidates"); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function changeRange(range: Report["range"]) { setLoading(true); setError(null); try { const next = await adminRequest<Report>(`/api/admin/reports?range=${range}`, { cache: "no-store" }); setReport(next); window.history.replaceState(null, "", `/admin/reports?range=${range}`); } catch (value) { setError(value instanceof Error ? value.message : "Reports could not be refreshed."); } finally { setLoading(false); } }
  return <div className="admin-page"><section className="admin-hero compact"><p className="page-kicker">Measured Activity</p><h1>Reports <span className="title-seal" aria-hidden="true">问候</span></h1><p>Explore persisted platform activity. Empty periods remain empty—no example curve is generated.</p></section>{error ? <div className="inline-feedback error" role="alert">{error}</div> : null}<section className="admin-report-controls"><label>Time range<select value={report.range} disabled={loading} onChange={(event) => void changeRange(event.target.value as Report["range"])}><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option></select></label></section><section className="admin-metric-grid report-metrics">{metricDefinitions.map(({ key, label, icon: Icon }) => <article className="admin-metric-card" key={key}><span><Icon size={27} /></span><div><small>{label}</small><strong>{report.totals[key].toLocaleString("en-US")}</strong><em className="neutral">Current database fact</em></div></article>)}</section><section className="admin-card admin-report-chart"><header><div><h2>Platform Activity</h2><small>UTC daily event buckets</small></div></header><div className="admin-series-tabs">{(Object.keys(trendLabels) as TrendKey[]).map((key) => <button key={key} type="button" className={series === key ? "active" : ""} onClick={() => setSeries(key)}>{trendLabels[key]}</button>)}</div>{report.hasData ? <AdminTrendChart points={report.trend} series={series} /> : <div className="admin-empty large"><TrendingUp size={31} /><h2>No activity in this range</h2><p>The chart is intentionally empty rather than populated with sample values.</p></div>}</section><section className="admin-distribution-grid"><Distribution title="Candidate status" rows={report.distributions.candidateStatus} /><Distribution title="Publication status" rows={report.distributions.publicationStatus} /><Distribution title="Review status" rows={report.distributions.reviewStatus} /><Distribution title="AI outcomes" rows={report.distributions.aiOutcomes} /></section></div>;
}

function Distribution({ title, rows }: { title: string; rows: Array<{ status?: string; outcome?: string; count: number }> }) { const total = rows.reduce((sum, row) => sum + row.count, 0); return <section className="admin-card admin-distribution"><header><h2>{title}</h2><strong>{total}</strong></header>{rows.length === 0 ? <p>No recorded data.</p> : <ul>{rows.map((row) => <li key={row.status ?? row.outcome}><span>{(row.status ?? row.outcome)?.replaceAll("_", " ")}</span><strong>{row.count}</strong><i style={{ width: `${total === 0 ? 0 : (row.count / total) * 100}%` }} /></li>)}</ul>}</section>; }
