import { Bot, FileSearch, Search, UsersRound } from "lucide-react";
import Link from "next/link";
import type { ReactNode } from "react";

import { searchAdminWorkspace } from "@/server/admin/search-service";

export const dynamic = "force-dynamic";

export default async function AdminSearchPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const query = ((await searchParams).q ?? "").trim().slice(0, 120);
  const results = query.length >= 2 ? await searchAdminWorkspace(query) : null;
  const total = results ? results.candidates.length + results.agents.length + results.reviews.length : 0;
  return <div className="admin-page"><section className="admin-hero compact"><p className="page-kicker">Safe Cross-domain Lookup</p><h1>Search <span className="title-seal" aria-hidden="true">问候</span></h1><p>Search account governance fields, public Agent identity, and risk safe summaries.</p></section><form className="admin-search-page-form" action="/admin/search"><Search size={20} /><label className="sr-only" htmlFor="admin-search-page">Search Admin workspace</label><input id="admin-search-page" name="q" defaultValue={query} minLength={2} maxLength={120} required autoFocus placeholder="Candidate, Agent, or safe review summary" /><button>Search</button></form>{query.length > 0 && query.length < 2 ? <div className="inline-feedback error">Enter at least 2 characters.</div> : null}{results ? <><p className="admin-search-summary">{total} result{total === 1 ? "" : "s"} for “{query}”</p><div className="admin-search-results"><SearchGroup title="Candidates" icon={UsersRound} empty="No Candidate accounts match.">{results.candidates.map((candidate) => <Link href={`/admin/candidates?search=${encodeURIComponent(candidate.displayName as string)}`} key={candidate.id as string}><strong>{candidate.displayName as string}</strong><small>{candidate.email as string} · {candidate.status as string}</small></Link>)}</SearchGroup><SearchGroup title="Published Agents" icon={Bot} empty="No published Agents match.">{results.agents.map((agent) => <Link href={`/admin/agents?search=${encodeURIComponent(agent.slug as string)}`} key={agent.id as string}><strong>{agent.displayName as string}</strong><small>{agent.headline as string || agent.slug as string} · {agent.status as string}</small></Link>)}</SearchGroup><SearchGroup title="Content Reviews" icon={FileSearch} empty="No safe review summaries match.">{results.reviews.map((review) => <Link href={`/admin/reviews?search=${encodeURIComponent(review.category as string)}`} key={review.id as string}><strong>{String(review.category).replaceAll("_", " ")}</strong><small>{review.safeSummary as string}</small></Link>)}</SearchGroup></div></> : <div className="admin-empty large"><Search size={31} /><h2>Search the governance workspace</h2><p>Private Source Material, Chunk text, and message content are not searchable here.</p></div>}</div>;
}

function SearchGroup({ title, icon: Icon, empty, children }: { title: string; icon: typeof UsersRound; empty: string; children: ReactNode }) { const hasResults = Array.isArray(children) ? children.length > 0 : Boolean(children); return <section className="admin-card admin-search-group"><header><Icon size={20} /><h2>{title}</h2></header>{hasResults ? <div>{children}</div> : <p>{empty}</p>}</section>; }
