import { BadgeCheck, KeyRound, ShieldCheck } from "lucide-react";

import { createTranslator } from "@/i18n/core";
import { getRequestLocale } from "@/i18n/server";
import { requirePageUser } from "@/server/auth/current";

export default async function AccountPage({ searchParams }: { searchParams: Promise<{ changed?: string; error?: string; profile?: string; profileError?: string; returnTo?: string }> }) {
  const [user, { changed, error, profile, profileError, returnTo }, locale] = await Promise.all([requirePageUser("candidate"), searchParams, getRequestLocale()]);
  const t = createTranslator(locale);
  const safeReturnTo = returnTo === "/workspace/agent" ? returnTo : "";
  return <section className="account-security-page"><header><div><p className="page-kicker">{t("account.kicker")}</p><h1>{t("account.title")}</h1><p>{t("account.copy")}</p></div><span><ShieldCheck size={28} /></span></header><div className="account-card-grid"><article className="account-security-card" id="public-profile"><div><strong>{t("account.profile.title")}</strong><small>{t("account.profile.copy")}</small></div>{profile ? <p className="form-success" role="status">{t("account.profile.changed")}</p> : null}{profileError ? <p className="form-error" role="alert">{t("account.profile.invalid")}</p> : null}<form action="/api/auth/profile" method="post">{safeReturnTo ? <input type="hidden" name="returnTo" value={safeReturnTo} /> : null}<label htmlFor="displayName">{t("account.profile.displayName")}</label><input id="displayName" name="displayName" defaultValue={user.displayName} maxLength={120} required /><label htmlFor="headline">{t("account.profile.headline")}</label><input id="headline" name="headline" defaultValue={user.headline ?? ""} maxLength={160} required aria-describedby="headline-help" /><small id="headline-help">{t("account.profile.headlineHelp")}</small><label htmlFor="location">{t("account.profile.location")}</label><input id="location" name="location" defaultValue={user.location ?? ""} maxLength={160} /><label htmlFor="bio">{t("account.profile.bio")}</label><textarea id="bio" name="bio" defaultValue={user.bio ?? ""} maxLength={2000} rows={6} /><button className="primary-button" type="submit"><BadgeCheck size={17} /> {t(safeReturnTo ? "account.profile.saveAndReturn" : "account.profile.submit")}</button></form></article><article className="account-security-card"><div><strong>{t("account.security.title")}</strong><small>{user.email}</small></div>{changed ? <p className="form-success" role="status">{t("account.changed")}</p> : null}{error ? <p className="form-error" role="alert">{t(error === "reuse" ? "account.reuse" : "account.currentInvalid")}</p> : null}<form action="/api/auth/password" method="post"><label htmlFor="currentPassword">{t("account.currentPassword")}</label><input id="currentPassword" name="currentPassword" type="password" autoComplete="current-password" maxLength={200} required /><label htmlFor="newPassword">{t("account.newPassword")}</label><input id="newPassword" name="newPassword" type="password" autoComplete="new-password" minLength={12} maxLength={200} required /><small>{t("auth.passwordHint")}</small><label htmlFor="confirmPassword">{t("auth.confirmPassword")}</label><input id="confirmPassword" name="confirmPassword" type="password" autoComplete="new-password" minLength={12} maxLength={200} required /><button className="primary-button" type="submit"><KeyRound size={17} /> {t("account.submit")}</button></form></article></div></section>;
}
